/*
 * generated by Xtext
 */
package org.eclipse.xtext.formatting2.partialformatting;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PartialFormattingTestLanguageRuntimeModule extends AbstractPartialFormattingTestLanguageRuntimeModule {
}
