/*
 * generated by Xtext
 */
package org.eclipse.xtext.formatting2.partialformatting;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PartialFormattingTestLanguageStandaloneSetup extends PartialFormattingTestLanguageStandaloneSetupGenerated {

	public static void doSetup() {
		new PartialFormattingTestLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
