/*******************************************************************************
 * Copyright (c) 2017 itemis AG (http://www.itemis.eu) and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 *******************************************************************************/
grammar org.eclipse.xtext.formatting2.partialformatting.PartialFormattingTestLanguage with org.eclipse.xtext.common.Terminals

generate partialformattingtestlanguage "http://formatter2/partialformattingtestlanguage"

Model:
	entities+=Entity*
;
	
Entity:
	"entity" name=ID "{"
		properties+=Property*
	"}"
;

Attribute:
	"attr" name=ID ":" type=SimpleType
;

enum SimpleType:
	String | Int | Bool
;

Reference:
	"ref" name=ID ":" entity=[Entity]
;

Property:
	Attribute | Reference
;