/*
 * generated by Xtext
 */
package org.eclipse.xtext.xtext.generator.parser.antlr.splitting;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.ISetup;
import org.eclipse.xtext.common.TerminalsStandaloneSetup;
import org.eclipse.xtext.xtext.generator.parser.antlr.splitting.simpleExpressions.SimpleExpressionsPackage;

@SuppressWarnings("all")
public class SimpleExpressionsStandaloneSetupGenerated implements ISetup {

	@Override
	public Injector createInjectorAndDoEMFRegistration() {
		TerminalsStandaloneSetup.doSetup();

		Injector injector = createInjector();
		register(injector);
		return injector;
	}
	
	public Injector createInjector() {
		return Guice.createInjector(new SimpleExpressionsRuntimeModule());
	}
	
	public void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.eclipse.org/xtext/xtext/generator/parser/antlr/simpleExpressions")) {
			EPackage.Registry.INSTANCE.put("http://www.eclipse.org/xtext/xtext/generator/parser/antlr/simpleExpressions", SimpleExpressionsPackage.eINSTANCE);
		}
	}
}
