/*
 * generated by Xtext
 */
package org.eclipse.xtext.formatting2.partialformatting.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.formatting2.partialformatting.parser.antlr.internal.InternalPartialFormattingTestLanguageParser;
import org.eclipse.xtext.formatting2.partialformatting.services.PartialFormattingTestLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class PartialFormattingTestLanguageParser extends AbstractAntlrParser {

	@Inject
	private PartialFormattingTestLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPartialFormattingTestLanguageParser createParser(XtextTokenStream stream) {
		return new InternalPartialFormattingTestLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public PartialFormattingTestLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PartialFormattingTestLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
