/*
 * generated by Xtext
 */
package org.eclipse.xtext.formatting2.partialformatting.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PartialFormattingTestLanguageAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/xtext/formatting2/partialformatting/parser/antlr/internal/InternalPartialFormattingTestLanguage.tokens");
	}
}
